config/routes.rb
Rails.application.routes.draw do
  get 'hello/index'

  get 'feelings/index'

  resources :hostels
  resources :winners
  resources :movies
  resources :stories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/winner.rb
class Winner < ApplicationRecord
end

app/controllers/winners_controller.rb
class WinnersController < ApplicationController
  before_action :set_winner, only: [:show, :edit, :update, :destroy]

  # GET /winners
  # GET /winners.json
  def index
    @winners = Winner.all
  end

  # GET /winners/1
  # GET /winners/1.json
  def show
  end

  # GET /winners/new
  def new
    @winner = Winner.new
  end

  # GET /winners/1/edit
  def edit
  end

  # POST /winners
  # POST /winners.json
  def create
    @winner = Winner.new(winner_params)

    respond_to do |format|
      if @winner.save
        format.html { redirect_to @winner, notice: 'Winner was successfully created.' }
        format.json { render :show, status: :created, location: @winner }
      else
        format.html { render :new }
        format.json { render json: @winner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /winners/1
  # PATCH/PUT /winners/1.json
  def update
    respond_to do |format|
      if @winner.update(winner_params)
        format.html { redirect_to @winner, notice: 'Winner was successfully updated.' }
        format.json { render :show, status: :ok, location: @winner }
      else
        format.html { render :edit }
        format.json { render json: @winner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /winners/1
  # DELETE /winners/1.json
  def destroy
    @winner.destroy
    respond_to do |format|
      format.html { redirect_to winners_url, notice: 'Winner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_winner
      @winner = Winner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def winner_params
      params.require(:winner).permit(:w_name, :w_goal, :w_description)
    end
end

app/helpers/winners_helper.rb
module WinnersHelper
end

app/views/winners/_form.html.erb
<%= form_with(model: winner, local: true) do |form| %>
  <% if winner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(winner.errors.count, "error") %> prohibited this winner from being saved:</h2>

      <ul>
      <% winner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :w_name %>
    <%= form.text_field :w_name, id: :winner_w_name %>
  </div>

  <div class="field">
    <%= form.label :w_goal %>
    <%= form.text_field :w_goal, id: :winner_w_goal %>
  </div>

  <div class="field">
    <%= form.label :w_description %>
    <%= form.text_area :w_description, id: :winner_w_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/winners/edit.html.erb
<h1>Editing Winner</h1>

<%= render 'form', winner: @winner %>

<%= link_to 'Show', @winner %> |
<%= link_to 'Back', winners_path %>

app/views/winners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Winners</h1>

<table>
  <thead>
    <tr>
      <th>W name</th>
      <th>W goal</th>
      <th>W description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @winners.each do |winner| %>
      <tr>
        <td><%= winner.w_name %></td>
        <td><%= winner.w_goal %></td>
        <td><%= winner.w_description %></td>
        <td><%= link_to 'Show', winner %></td>
        <td><%= link_to 'Edit', edit_winner_path(winner) %></td>
        <td><%= link_to 'Destroy', winner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Winner', new_winner_path %>

app/views/winners/new.html.erb
<h1>New Winner</h1>

<%= render 'form', winner: @winner %>

<%= link_to 'Back', winners_path %>

app/views/winners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>W name:</strong>
  <%= @winner.w_name %>
</p>

<p>
  <strong>W goal:</strong>
  <%= @winner.w_goal %>
</p>

<p>
  <strong>W description:</strong>
  <%= @winner.w_description %>
</p>

<%= link_to 'Edit', edit_winner_path(@winner) %> |
<%= link_to 'Back', winners_path %>